#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Satoru Homma
# SPDX-License-Identifier: BSD-3-Clause


import sys

def hitting_score():
    data = sys.stdin.read().strip()
    hits, boxes, sacrifices, walks = [int(x) for x in data.split(",")]
    
    if boxes == 0:
        print("君はベンチ")
        return
    elif boxes < hits + sacrifices + walks:
        print("打席数が安打・犠打・犠飛数と四死球数より少ないです。")
        return
    elif boxes - sacrifices - walks == 0 and hits == 0:
        print("全打席四死球or全打席犠打・犠飛の生きる伝説です。")
        return
    
    batting_average = hits / (boxes - sacrifices - walks)

    if batting_average > 1.0:
        print("それは強すぎる")
        return
    print(f"{batting_average:.3f}")

if __name__ == "__main__":
    hitting_score()
