#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Satoru Homma
# SPDX-License-Identifier: BSD-3-Clause


import sys

def pitching_score():
    data = sys.stdin.read().strip()

    if not all(x.isdigit() for x in data.split(",")):
        print("入力に自然数以外が含まれています")
        return
    innings, earned_runs, fractions = [int(x) for x in data.split(",")]

    if innings == 0 and fractions == 0:
        print("監督「君はそもそもベンチだぞ」")
        return
    
    if fractions == 1:
        pitching_innings = innings + 1 / 3
    elif fractions == 2:
        pitching_innings = innings + 2 / 3
    elif fractions == 0:
        pitching_innings = innings
    else :
       print("監督「投球回数の端数は３未満の自然数だ。」")
       return

    print(f"{round(era, 3):.3f}")

if __name__ == "__main__":
    pitching_score()
